### ISSUE TITLE
Connectivity issues from within docker on CoreOS

### ISSUE THREAD

**Issue by brycekahle** [coreos/go-etcd#167] opened 2014-10-29 22:48 UTC
I use go-etcd from within docker containers to talk to etcd on the host CoreOS machine. I get this error very frequently on startup
`501: All the given peers are not reachable (Tried to connect to each peer twice and failed)`

I am using `http://172.17.42.1:4001` for the `machines` argument to `NewClient`. Thoughts?

**Comment by zyndiecate** [comment] 2015-01-09 18:34
We experiencing this on our coreos clusters too with the exact same error. Everything works fine, but then a node is leaving the cluster and another joins. Then, applications using `go-etcd` cannot reconnect to etcd anymore. That is really weird because there are just simple HTTP requests made.

Does anybody have a solution for this? I am not able to reproduce it on ubuntu with starting/stopping etcd.

**Comment by yichengq** [comment] 2015-01-10 20:44
It indicates that go-etcd has attempted enough times and still cannot
connect to the cluster and make the request successfully.

You should check the status of the cluster to see what actually happens.

Moreover, we are moving to 2.0-alpha release now. Welcome to give it a try.

Yicheng

**Comment by zyndiecate** [comment] 2015-01-10 20:45
That is the thing. When going into the container I am able to connect to etcd.

**Comment by brosner** [comment] 2015-01-28 19:15
I am seeing this problem. I've confirmed the issue is not the network. It doesn't even try more than once! Here is some log output:

```
go-etcd2015/01/28 18:52:59 DEBUG: put /services/redis, {"Host":"10.1.17.64","Port":49173}, ttl: 60, [http://10.1.17.1:4001]
go-etcd2015/01/28 18:52:59 DEBUG: Connecting to etcd: attempt 1 for keys/services/redis
go-etcd2015/01/28 18:52:59 DEBUG: send.request.to http://10.1.17.1:4001/v2/keys/services/redis | method PUT
go-etcd2015/01/28 18:52:59 DEBUG: recv.response.from http://10.1.17.1:4001/v2/keys/services/redis
error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

I tracked this down to happening only when there is a single node in the peer list. When I added the same node twice in the peer list to workaround failing on the first attempt I now see:

```
go-etcd2015/01/28 19:06:30 DEBUG: put /services/redis, {"Host":"10.1.17.67","Port":49174}, ttl: 60, [http://10.1.17.1:4001]
go-etcd2015/01/28 19:06:30 DEBUG: Connecting to etcd: attempt 1 for keys/services/redis
go-etcd2015/01/28 19:06:30 DEBUG: send.request.to http://10.1.17.1:4001/v2/keys/services/redis | method PUT
go-etcd2015/01/28 19:06:31 DEBUG: network error: Put http://10.1.17.1:4001/v2/keys/services/redis: dial tcp 10.1.17.1:4001: i/o timeout
go-etcd2015/01/28 19:06:31 WARNING: bad response status code0
go-etcd2015/01/28 19:06:32 DEBUG: Connecting to etcd: attempt 2 for keys/services/redis
go-etcd2015/01/28 19:06:32 DEBUG: send.request.to http://10.1.17.1:4001/v2/keys/services/redis | method PUT
go-etcd2015/01/28 19:06:32 DEBUG: recv.response.from http://10.1.17.1:4001/v2/keys/services/redis
go-etcd2015/01/28 19:06:32 WARNING: bad response status code307
go-etcd2015/01/28 19:06:32 DEBUG: Connecting to etcd: attempt 3 for keys/services/redis
go-etcd2015/01/28 19:06:32 DEBUG: send.request.to http://10.1.17.1:4001/v2/keys/services/redis | method PUT
go-etcd2015/01/28 19:06:32 DEBUG: recv.response.from http://10.1.17.1:4001/v2/keys/services/redis
error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

It looks like etcd is returning a temporary redirect. When I attempted the same from the host I saw the same behavior and the `Location` value appears to be the private IP. This is a no go within the container.

I wanted to document my experience thus far. I am now going down the stack to work out what is either an issue with etcd (possibly configuration).

**Comment by brosner** [comment] 2015-01-28 19:32
Turns out my issue was the removal of redirection in 5348c80bde6223fa53c48ef546b4802db69b1d70. Not quite sure how it is supposed to work now.

**Comment by yichengq** [comment] 2015-02-01 18:19
@brosner The 5348c80bde6223fa53c48ef546b4802db69b1d70 is written for v2.0 compatibility. I have tagged the v0.4.6 tag, and please use that for v0.4.6 etcd cluster.
The message indicates that client cannot connect to the cluster, and user should check the status of the cluster.
Thanks for digging and reporting!

**Closed by yichengq** 2015-02-01 18:19 UTC
